#!/usr/bin/env python

import sys

from smile_mobile_gui.position_plotter import Position_Plotter
from rqt_gui.main import Main

plugin = 'smile_mobile_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
